chore(dev) add theme picker to the developer tool
highlightjs/highlight.js pull request #2770
Opened 2020-10-18 13:33 UTC by joshgoebel

Adds theme picker to tools/developer.html, makes it easier to see how
various themes look when developing/improving language grammars.

### Changes

### Checklist
- [x] Added markup tests, or they don't apply because developer tool...
- [ ] Updated the changelog at `CHANGES.md`
- [x] Added myself to `AUTHORS.txt`, under Contributors

2020-10-21 02:59 UTC, allejo requested changes

2020-10-21 02:59 UTC, allejo commented on tools/developer.html
> +            theme: localStorage.getItem(key_THEME),
```suggestion
            theme: localStorage.getItem(key_THEME) || 'default.css',
```

The page loads without a default style if we rely solely on local storage.

2020-10-21 02:59 UTC, allejo commented on tools/developer.html
> +          editor.hasClass('visible-structure'));
```suggestion
        localStorage.setItem(key_STRUCTURE, editor.hasClass('visible-structure'));
```

not sure why this was on two lines

2020-10-23 22:23 UTC, joshgoebel commented on tools/developer.html
> +          editor.hasClass('visible-structure'));
Not sure it mattered, but ok. :)

2020-10-23 22:25 UTC, merged