(powershell) Add three VALID_VERBS and update the reference link (#2981)
highlightjs/highlight.js pull request #2982
Opened 2021-01-30 22:41 UTC by davidhcefx

Resolves #2981 

### Changes

- Added three [officially-approved verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.1) into `VALID_VERBS`:
  - `Mount`
  - `Build`
  - `Deploy`
- Update the reference link to: `https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands`.

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`
- [ ] Added myself to `AUTHORS.txt`, under Contributors

2021-01-31 06:33 UTC, joshgoebel commented
Will try to review on laptop tomorrow. Looked good at a glance.

2021-02-05 04:12 UTC, joshgoebel commented
Looks good.  Please finish updating the changelog then we could merge.

2021-02-07 03:49 UTC, davidhcefx commented
@joshgoebel I’ve complete updating `UPDATE.md`

2021-02-07 07:14 UTC, joshgoebel requested changes

2021-02-07 07:14 UTC, joshgoebel commented on CHANGES.md
> +- enh(powershell) Add three VALID_VERBS and update the reference link (#2981) [davidhcefx][]
Please also add yourself around line 40 so the `davidhcefx` link actually works.

2021-02-07 07:32 UTC, davidhcefx commented on CHANGES.md
> +- enh(powershell) Add three VALID_VERBS and update the reference link (#2981) [davidhcefx][]
Oh, I didn’t realize it’s a different markdown syntax. Thanks!

2021-02-07 07:40 UTC, joshgoebel approved these changes

2021-02-07 07:41 UTC, merged

2021-02-07 07:41 UTC, joshgoebel commented
Thanks!