enh(js/ts) improve CLASS_REFERANCE, add TS keywords
highlightjs/highlight.js pull request #3411
Opened 2021-11-29 19:04 UTC by joshgoebel

Resolves #3403.

### Changes

- adding some missing TS keywords
- improves CLASS_NAME_REFERNCE rule to catch more edge cases

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

2021-12-06 21:30 UTC, joshgoebel commented on src/languages/typescript.js
> +    "unknown"
```suggestion
    "enum"
```

2021-12-06 21:30 UTC, joshgoebel commented on src/languages/typescript.js
> +    "keyof"
```suggestion
    "readonly"
```

2021-12-09 07:43 UTC, allejo requested changes
Missing the edge case of a class matching the "CSSFactory" rule and ending with an uppercase letter; e.g. `HTTPResponseT` or `IResponseTsS`

![image](https://user-images.githubusercontent.com/1246453/145354423-123ee4cf-971a-45c6-a593-5c2fe54dc815.png)

2021-12-09 18:24 UTC, allejo approved these changes
lgtm :+1:

2021-12-09 18:26 UTC, merged