Add Apex to supported languages
highlightjs/highlight.js pull request #3546
Opened 2022-05-31 19:22 UTC by dschach

Add Apex (Salesforce) language

### Changes
Include Apex in table

### Checklist
- [ ] Added markup tests, or they don't apply here because... All tests are in the repo
- [ ] Updated the changelog at `CHANGES.md`

2022-06-01 06:04 UTC, dschach commented
Apex is now also on NPM (and all the CDN services automatically). 
https://www.npmjs.com/package/highlightjs-apex

2022-06-12 12:47 UTC, joshgoebel requested changes

2022-06-12 16:19 UTC, dschach commented on CHANGES.md
> +- Added 3rd party Apex grammar to SUPPORTED_LANGUAGES (#3546) [David Schach](https://github.com/dschach)
That was already fixed, I believe.

2022-06-12 16:20 UTC, dschach commented on SUPPORTED_LANGUAGES.md
> +| Apex                    | lightning              |[highlightjs-apex](https://github.com/highlightjs/highlightjs-apex/)  |
Done

2022-06-15 04:10 UTC, joshgoebel commented
Please do not reformat the entire markdown file, just add the single line you need (so the diff is clear on what's changed), it's doesn't matter whether the brackets are perfect or not in the ASCII form just so long as it render fine on GitHub...

2022-06-15 19:32 UTC, dschach commented
Fixed. Ready for review.

2022-06-15 19:59 UTC, joshgoebel approved these changes
Thanks so much! Perfect!

2022-06-15 20:07 UTC, merged