Add C23 keywords and types
highlightjs/highlight.js pull request #3836
Opened 2023-08-08 20:21 UTC by Eisenwave

### Changes

This PR adds a few keywords that have been introduces in C23. Firstly, C now also has `constexpr` and the preprocessor got `#elifdef` and `#elifndef`. See https://en.cppreference.com/w/c/23.

Secondly, there are numerous extended floating point types (not yet documented on cppreference). See [N3096 H.5.1 Keywords](https://open-std.org/JTC1/SC22/WG14/www/docs/n3096.pdf).

### Checklist
- [x] Added markup tests, or they don't apply here because this is a simple expansion of the keyword list
- [x] Updated the changelog at `CHANGES.md`

2024-01-14 15:04 UTC, TOMWT-qwq approved these changes
CHANGES.md is out of date.

2024-01-14 21:07 UTC, joshgoebel commented on CHANGES.md
> +- enh(c) added more C23 keywords and preprcoessor directives [Eisenwave][]
You also need to add the link on lines 44-53.

2024-01-14 21:08 UTC, joshgoebel requested changes
Looks good except for changelog link!

2024-01-14 21:09 UTC, joshgoebel commented
You can merge or rebase on latest to get newest changelog.

2024-03-21 00:56 UTC, joshgoebel approved these changes

2024-03-21 00:57 UTC, merged