Makefile String Fix
highlightjs/highlight.js pull request #3898
Opened 2023-10-22 08:47 UTC by aneesh98

Resolves #3878 
### Changes

1. I have modified the FUNC configuration for Makefile to include QUOTE_STRING so appropriate highlighting gets applied to the string mentioned within a function context

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

2023-10-23 01:49 UTC, TriMoon commented
See my reply: https://github.com/highlightjs/highlight.js/issues/3878#issuecomment-1774302718

2023-10-23 01:51 UTC, TriMoon requested changes
See my reply: https://github.com/highlightjs/highlight.js/issues/3878#issuecomment-1774302718

2024-03-21 01:31 UTC, joshgoebel approved these changes

2024-03-21 01:31 UTC, joshgoebel commented
Can you update the changelog?

2024-05-07 00:45 UTC, joshgoebel commented
ping

2024-07-07 02:51 UTC, joshgoebel commented
Looks good.   Can you please merge/rebase and add attribution to CHANGELOG?

2024-07-07 02:55 UTC, joshgoebel approved these changes

2024-07-07 02:56 UTC, merged