enh(cpp) add numbers to preprocessor scope
highlightjs/highlight.js pull request #3930
Opened 2023-11-20 03:40 UTC by joshgoebel

### Changes

### Checklist
- [ ] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

2024-01-14 14:53 UTC, TOMWT-qwq approved these changes

2024-01-14 14:55 UTC, TOMWT-qwq approved these changes

2024-01-14 14:58 UTC, TOMWT-qwq requested changes
Seem Checklist forgotten.

2024-01-14 20:31 UTC, joshgoebel commented
Lets add a markup test for this as well, and would this also make sense to apply to C?

2024-01-24 14:46 UTC, TOMWT-qwq reviewed
https://github.com/highlightjs/highlight.js/pull/3975 I've done chores for you.

2024-03-21 01:47 UTC, closed without merging