Cybertopia
highlightjs/highlight.js pull request #4124
Opened 2024-09-30 22:14 UTC by noraj

New theme with 4 variants, source here (with screenshots): https://github.com/noraj/cybertopia-highlightjs

2024-09-30 22:58 UTC, joshgoebel commented on src/styles/cybertopia-cherry.css
> +}
Please exclude this, our build system will add the base styling automatically.

2024-09-30 22:59 UTC, joshgoebel requested changes
see comments

2024-10-01 12:28 UTC, Theghost256 approved these changes

2024-10-20 19:51 UTC, joshgoebel commented
I almost forgot about `checkTheme.js`... please run it and add the few missing styles to your theme.  You can ignore the optional ones if you really want, but we'd like to see all the non-optional ones to include new themes here.

I'll also try to find the time to fix the accessibiltiy checks to work with variables - since we also care about the accessibility of our themes out of the box.

2024-10-29 21:24 UTC, noraj commented
Great suggestion, I'll run [checkTheme.js](https://github.com/highlightjs/highlight.js/blob/main/tools/checkTheme.js) as asked in [theme-guide](https://github.com/highlightjs/highlight.js/blob/2bd6ff65635640c99b04cd4217cfe45ca682f884/docs/theme-guide.rst#L52) and add the missing styles.

For accessibility, I checked the contrast against WCAG at https://webaim.org/resources/contrastchecker/.

2024-10-31 21:08 UTC, joshgoebel approved these changes

2024-10-31 21:09 UTC, joshgoebel commented
Could you please rebase to resolve conflicts?

2024-10-31 21:59 UTC, joshgoebel approved these changes

2024-10-31 21:59 UTC, merged

2024-10-31 22:00 UTC, noraj commented
Thank you for the guidance.