Add the `using` keyword per the "Explicit Resource Management" proposal
highlightjs/highlight.js pull request #4135
Opened 2024-10-10 22:05 UTC by sufianrhazi

### Changes

This ECMAScript proposal adds a new keyword (`using`). It's reached stage 3, which is "recommended for implementation":
* Proposal: https://github.com/tc39/proposal-explicit-resource-management
* ECMAScript proposal process: https://tc39.es/process-document/

The change itself is very small, I've just added the `using` keyword to the list of keywords in `src/languages/lib/ecmascript.js`. I've also updated an existing keyword test adding a case to ensure `using` is rendered as `<span class="hljs-keyword">using</span>` in a declaration.

I didn't update the `CHANGES.md`, since I'm not sure if I should cut a new version for this? But let me know what to do and I can do it.

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [ ] Updated the changelog at `CHANGES.md`

2024-10-20 19:32 UTC, joshgoebel commented on src/languages/lib/ecmascript.js
> +  "using"
```suggestion
  "extends",
  // It's reached stage 3, which is "recommended for implementation":
  "using"
```

2024-10-20 19:32 UTC, joshgoebel requested changes
Lets add the comment then this is good to merge!

2024-10-24 13:57 UTC, sufianrhazi commented
Thank you! Just added the suggested changes.

2024-10-24 21:45 UTC, joshgoebel approved these changes

2024-10-24 21:47 UTC, merged