fix(swift) - add proper syntax highlighting for class func/var declarations
highlightjs/highlight.js pull request #4154
Opened 2024-10-29 23:43 UTC by guuido

Fixes the syntax highlighting for class functions and variables

Resolves #4121

### Changes
Before the declaration of `class func` and `class var` was not handled correctly, for example
```swift
class func foo() async throws -> [Bar]
class var someProperty: Int { get }
```
was interpreted as
```html
<span class="hljs-keyword">class</span> <span class="hljs-title class_">func</span> foo() <span class="hljs-keyword">async</span> <span class="hljs-keyword">throws</span> -&gt; [<span class="hljs-type">Bar</span>]
<span class="hljs-keyword">class</span> <span class="hljs-title class_">var</span> someProperty: <span class="hljs-type">Int</span> { <span class="hljs-keyword">get</span> }
```
After the fix the result is the following:
```html
<span class="hljs-keyword">class </span><span class="hljs-keyword">func</span> <span class="hljs-title function_">foo</span>() <span class="hljs-keyword">async</span> <span class="hljs-keyword">throws</span> -&gt; [<span class="hljs-type">Bar</span>]
<span class="hljs-keyword">class </span><span class="hljs-keyword">var</span> someProperty: <span class="hljs-type">Int</span> { <span class="hljs-keyword">get</span> }
```

### Checklist
- [x] Added markup tests, or they don't apply here because...
- [x] Updated the changelog at `CHANGES.md`

2024-10-30 06:22 UTC, joshgoebel commented on src/languages/swift.js
> +      /(func)\b/,
You shouldn't need the `()`.

2024-10-30 06:22 UTC, joshgoebel commented on src/languages/swift.js
> +      /(class)\s+/,
Please split out the `\s+` as you did above.

2024-10-30 06:23 UTC, joshgoebel commented on src/languages/swift.js
> +    beginScope: {
Pretty sure if there is no `end` you can use the simpler:

- `match`
- `scope`

2024-10-30 06:23 UTC, joshgoebel requested changes
Some small thoughts, but looks like we're headed the right direction.

2024-10-30 10:07 UTC, guuido commented
@joshgoebel thanks for your patience (it's my first contribution to the project), now it should be ok

2024-10-31 03:41 UTC, joshgoebel approved these changes
LGTM!

2024-10-31 03:42 UTC, merged